### PR TITLE
Fix issue with transitioning issues to "Done" state

### PR DESCRIPTION
**Pull request by slide**
Added a field input for the required "resolution" field.

### CODE REVIEW

**Comment by slide** [comment]
@oleg-nenashev @batmat Please review

**Comment by oleg-nenashev** [comment]
Sorry, I was traveling on this week

**Comment by oleg-nenashev** [comment]
👍 if it passes the manual tests

**Comment by slide** [comment]
Is there a way to dump the setup for the hosting project so it could be loaded into a test jira instance?

**Comment by oleg-nenashev** [comment]
Nope AFAIK. I've been just using my JIRA account and a test issue in the HOSTING project

**Comment by slide** [comment]
Was the transition to done not working when you were testing with your account? I thought that it worked under our user accounts, but not the ircbot account. I'll try it and see.

**Comment by slide** [comment]
I tested this manually (see [HOSTING-222](https://issues.jenkins-ci.org/projects/HOSTING/issues/HOSTING-222?filter=allissues) ) and it worked. My only concern is that the bot is a different user.

**Comment by oleg-nenashev** [comment]
It won't make the things worse, so we can test in prod

**Comment by batmat** [comment]
:+1: worse case, we revert to the previous version, it's not like there's data migration on the bot side or something.

**Pull request merged**
