### PR TITLE
Disable service hook creation

### PR DESCRIPTION
**Pull request by slide**
See http://lists.jenkins-ci.org/pipermail/jenkins-infra/2018-October/001576.html

### CODE REVIEW

**Comment by slide** [comment]
I kept it in so that if something needs to be added in the future, we can see where it was. I can definitely just remove it though.

**Comment by daniel-beck** [comment]
That's what the Git history is for.

**Comment by slide** [comment]
I know, I tell people at work that all the time and then fell for it myself. I feel so ashamed. ;-)

**Comment by daniel-beck** [comment]
Next step: Someone squashes this 😆

**Comment by slide** [comment]
You can squash while merging

**Comment by rtyler** [comment]
Squashing because I live to make @daniel-beck happy

**Pull request merged**
