### PR TITLE
Update to point to jenkins.io IRC bot doc

### PR DESCRIPTION
**Pull request by batmat**
\o/ @rtyler

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@batmat @rtyler Just in case, did you take ownership of the project?  IIRC I was its maintainer.The most of the docs are located on GitHub, so I'm not sure it makes sense to reference GitHub instead of Jenkins.io short page. BTW, if you are ready to maintain this component, feel free to do what you prefer

**Comment by batmat** [comment]
You're right @oleg-nenashev we should have waited more. @rtyler began experimenting moving doc from the wiki to jenkins.io and asked me to file the PR about the help page. That's just that, nothing more ATM.

**Comment by oleg-nenashev** [comment]
Wiki must die, of course. But I think the bot's GitHub repo is the best
place for docs

**Comment by rtyler** [comment]
@oleg-nenashev the link referenced points to the exact same content which was on the wiki, none of the developer docs were hosted on the wiki or touched here..

If you want all documentation to be in this repository then so be it. I'm fine with removing all references to the [IRC Bot from jenkins.io](https://jenkins.io/projects/infrastructure) if that's what you desire.

**Comment by oleg-nenashev** [comment]
Having a brief reference on jenkins.io is perfectly fine. I just want to avoid moving all the IRC bot documentation there

**Pull request merged**
