### PR TITLE
Extend jenkins-infra release drafter

### PR DESCRIPTION
**Pull request by NotMyFault**
The infra org provides the same template we can rely on.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by NotMyFault** [comment]
Btw, can you uninstall the release-drafter bot from this repo please?

**Comment by timja** [comment]
do you happen to know how if you don't have owner access to the org (I have admin on this repo)? I think there's a way but its non obvous.

**Comment by NotMyFault** [comment]
Maybe through the bot config page for orgs? https://github.com/apps/release-drafter/installations/new

**Comment by timja** [comment]
That works, removed, thanks

**Pull request merged**
