### PR TITLE
Don't disable GitHub issues by default

### PR DESCRIPTION
**Pull request by timja**
Lots of plugins are using GitHub issues now, would be good to not disable by default

### CODE REVIEW

**Comment by daniel-beck** [comment]
Opt in isn't a problem when the maintainers are repo admins. If they want to use it, they can; better than have nobody looking at issues there (sometimes a problem with Jira).

Perhaps we need a flag "where do you want to track issues?" in hosting, and act accordingly?

**Comment by timja** [comment]
> Perhaps we need a flag "where do you want to track issues?" in hosting, and act accordingly?

Sounds fine to me

**Comment by slide** [comment]
What is keeping us on Jira at all at this point? Cross component issues?

**Comment by daniel-beck** [comment]
> What is keeping us on Jira at all at this point?

The vast backlog of existing issues, cross component issues, core issues, issues for things that aren't deliverables in themselves, wrongly reported issues, security issues, infra issues.

**Comment by slide** [comment]
> > What is keeping us on Jira at all at this point?
> 
> The vast backlog of existing issues, cross component issues, core issues, issues for things that aren't deliverables in themselves, wrongly reported issues, security issues, infra issues.

Maybe it would be good to move plugins themselves to GitHub issues and have only core/Infra/etc in Jira for now? Jira is SOOOOOOO slow it's really hard to get things done. This is outside the scope of this issue I guess, so I'll stop with this thread.

**Comment by timja** [comment]
> > > What is keeping us on Jira at all at this point?
> > 
> > 
> > The vast backlog of existing issues, cross component issues, core issues, issues for things that aren't deliverables in themselves, wrongly reported issues, security issues, infra issues.
> 
> Maybe it would be good to move plugins themselves to GitHub issues and have only core/Infra/etc in Jira for now? Jira is SOOOOOOO slow it's really hard to get things done. This is outside the scope of this issue I guess, so I'll stop with this thread.

May as well continue it, been discussing with Olivier and Mark today.

I don't think there's any reason to keep INFRA on jira.

**Comment by olblak** [comment]
Discussion about this happening on the mailing list [here](https://groups.google.com/forum/#!topic/jenkinsci-dev/haFTYlhp7h8)

**Comment by daniel-beck** [comment]
> Discussion about this happening on the mailing list here

Yes, and the first post indicates that this thread was derailed really badly.

**Comment by daniel-beck** [comment]
> I don't think there's any reason to keep INFRA on jira.

Where would you expect users to report mirror problems, or problems with ci.jenkins.io? There's quite a few infra areas where corresponding GitHub repos don't exist, or, for users, are impossible to discover.

Giving up the issue tracker in favor of a mailing list and a manually maintained list of "Problem with X? Report on GitHub here!" mappings seems like a step backwards.

**Comment by slide** [comment]
@daniel-beck Can we add a field to Jira for HOSTING to allow the user to select Jira or Github for issue tracking? I'd like to have the field in place and then update the bot to support the field.

**Comment by daniel-beck** [comment]
@slide Sure, I can add that. Could you file an INFRA issue for me for this?

**Comment by slide** [comment]
Here you go https://issues.jenkins.io/browse/INFRA-2823

**Review by olblak — APPROVED** [review]

**Comment by slide** [comment]
I'm going to update the bot to check the new field created to see which issue tracker to use. I think that PR (coming soon) would supersede this one.

**Comment by slide** [comment]
I think this is superceded by my PR using the field in hosting issues.

**Pull request closed without merging**
