### PR TITLE
Add component list command

### PR DESCRIPTION
**Pull request by slide**
jenkins-admin: list components for slide_o_mix

### CODE REVIEW

**Comment by daniel-beck** [comment]
Spam-ban the bot for `list components for kohsuke`?

**Comment by slide** [comment]
Good point, I'll add some limits

**Comment by oleg-nenashev** [comment]
@slide do you plan to finish it? If no, maybe makes sense to keep it open so somebody finalizes it eventually

**Comment by slide** [comment]
No, I was abondoning it. Someone else could complete it if desired. I realized this feature is not really something I see a need for.

**Pull request closed without merging**
