### PR TITLE
Added option for someone with voice to kick a user.

### PR DESCRIPTION
**Pull request by christ66**
In the event a user is spamming the IRC channel this would grant anyone with voice the option to kick a user.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by christ66** [comment]
Added command to wiki page: https://wiki.jenkins-ci.org/display/JENKINS/IRC+Bot#IRCBot-Kickauser.

**Comment by oleg-nenashev** [comment]
ty.
I suppose the new bot version has not been released yet. I'll check it tomorrow

**Comment by christ66** [comment]
@oleg-nenashev I do not think kicking will work unless jenkins-admin is AOP.

**Comment by oleg-nenashev** [comment]
Yes, my experience with javabot is similar.
<code>jenkins-admin</code> initially was an AOP, but AFAIK it lost these permissions after the migration to Docker. Probably, @rtyler remembers the cause.

**Comment by orrc** [comment]
Kicking probably isn't much use anyway without also being able to ban, as javabot has been kicked a few times, but just re-joins later.

**Comment by oleg-nenashev** [comment]
"/mode #jenkins +b javabot" should work on FreeNode.

2015-02-06 13:39 GMT+03:00 Christopher Orr <notifications@github.com>:

**Comment by christ66** [comment]
@orrc If no one has any objections I can create a PR for banning also. I was just unsure if someone with `+v` would abuse the ban option or if their account was hacked and started banning everyone. If we really require a ban, then we should probably contact either AOP or the freenode staff.

**Pull request merged**
